# Generated by Django 5.0.7 on 2024-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Доступ разрешен', 'Доступ разрешен'), ('Отказано в доступе', 'Отказано в доступе'), ('Заявка не рассмотрена', 'Заявка не рассмотрена')], default='Заявка не рассмотрена', max_length=60)),
                ('telegram_id', models.CharField(blank=True, max_length=200, null=True)),
                ('subscription_expires_date', models.DateField(blank=True, null=True)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
