# Generated by Django 5.0.7 on 2024-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.SlugField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ALLOWED', 'Allowed'), ('DENIED', 'Denied'), ('NOT_VIEWED', 'Not Viewed')], default='Not Viewed', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
